global using IntelliTect.Coalesce;
global using IntelliTect.Coalesce.DataAnnotations;
global using IntelliTect.Coalesce.Models;
global using IntelliTect.SyncUp.Data.Auth;
global using IntelliTect.SyncUp.Data.Coalesce;
global using IntelliTect.SyncUp.Data.Models;
global using IntelliTect.SyncUp.Data.Utilities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Security.Claims;
global using static IntelliTect.Coalesce.DataAnnotations.SecurityPermissionLevels;
global using HttpMethod = IntelliTect.Coalesce.DataAnnotations.HttpMethod;
global using SearchMethods = IntelliTect.Coalesce.DataAnnotations.SearchAttribute.SearchMethods;
